itg/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from itg import settings
from news import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.MainView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('news/', include('news.urls', namespace='news')),
    path('users/', include('users.urls', namespace='users')),

    # Общие URL allauth
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

news/urls.py
from django.urls import path
from . import views


app_name = 'news'

# будет иметь префикс в urlах /news/
urlpatterns = [
    path('catalog/', views.GetAllNewsViews.as_view(), name='catalog'),
    path('catalog/<int:pk>/', views.ArticleDetailView.as_view(), name='detail_article_by_id'),
    path('catalog/<slug:slug>/', views.ArticleDetailView.as_view(), name='detail_article_by_slag'),
    path('tag/<int:tag_id>/', views.GetNewsByTagView.as_view(), name='get_news_by_tag'),
    path('category/<int:category_id>/', views.GetNewsByCategoryView.as_view(), name='get_news_by_category'),
    path('search/', views.SearchNewsView.as_view(), name='search_news'),
    path('like/<int:article_id>/', views.ToggleLikeView.as_view(), name='toggle_like'),
    path('favorite/<int:article_id>/', views.ToggleFavoriteView.as_view(), name='toggle_favorite'),
    path('favorites/', views.FavoritesView.as_view(), name='favorites'),
    path('add/', views.AddArtilceView.as_view(), name='add_article'),
    path('edit/<int:pk>/', views.ArticleUpdateView.as_view(), name='article_update'),
    path('delete/<int:pk>/', views.ArticleDeleteView.as_view(), name='article_delete'),
    path('upload_json/', views.UploadJsonView.as_view(), name='upload_json'),
    path('edit_article_from_json/<int:index>/', views.EditArticleFromJsonView.as_view(), name='edit_article_from_json'),
    path('subscribe/author/<int:author_id>/',  # POST
         views.ToggleAuthorSubscriptionView.as_view(),
         name='toggle_author_subscription'),
    path('subscribe/tag/<int:tag_id>/',        # POST
         views.ToggleTagSubscriptionView.as_view(),
         name='toggle_tag_subscription'),
]

news/models.py
import unidecode

from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import Q
from django.urls import reverse
from django.utils.text import slugify


class ArticleQuerySet(models.QuerySet):
    def active(self):
        return self.filter(is_active=True)

    def by_category(self, category_id):
        return self.active().filter(category_id=category_id)

    def by_tag(self, tag_id):
        return self.active().filter(tags__id=tag_id)

    def search(self, query):
        return self.active().filter(Q(title__icontains=query) | Q(content__icontains=query))

    def sorted(self, sort='publication_date', order='desc'):
        valid_sort_fields = {'publication_date', 'views'}
        if sort not in valid_sort_fields:
            sort = 'publication_date'
        order_by = f'-{sort}' if order == 'desc' else sort
        return self.active().order_by(order_by)


class AllArticleManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()


class ArticleManager(models.Manager):
    def get_queryset(self):
        return ArticleQuerySet(self.model, using=self._db)

    def active(self):
        return self.get_queryset().active()

    def by_category(self, category_id):
        return self.get_queryset().by_category(category_id)

    def by_tag(self, tag_id):
        return self.get_queryset().by_tag(tag_id)

    def search(self, query):
        return self.get_queryset().search(query)

    def sorted(self, sort='publication_date', order='desc'):
        return self.get_queryset().sorted(sort, order)


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name='Категория')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'Categories'  # без указания этого параметра, таблица в БД будет называться вида 'news_categorys'
        verbose_name = 'Категория'  # единственное число для отображения в админке
        verbose_name_plural = 'Категории'  # множественное число для отображения в админке
        ordering = ['name']  # указывает порядок сортировки модели по умолчанию

class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name='Тег')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'Tags'  # без указания этого параметра, таблица в БД будет называться вида 'news_tags'
        verbose_name = 'Тег'  # единственное число для отображения в админке
        verbose_name_plural = 'Теги'  # множественное число для отображения в админке


class Article(models.Model):
    class Status(models.IntegerChoices):
        UNCHECKED = 0, 'не проверено'
        CHECKED = 1, 'проверено'

    title = models.CharField(max_length=255, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Содержание')
    publication_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')
    views = models.IntegerField(default=0, verbose_name='Просмотры')
    category = models.ForeignKey('Category', on_delete=models.CASCADE, default=1, verbose_name='Категория')
    tags = models.ManyToManyField('Tag', related_name='article', verbose_name='Теги')
    slug = models.SlugField(unique=True, blank=True, verbose_name='Слаг')
    is_active = models.BooleanField(default=True, verbose_name='Активна')

    status = models.BooleanField(default=0,
                                 choices=(map(lambda x: (bool(x[0]), x[1]), Status.choices)),
                                 verbose_name='Проверено')

    author = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, default=None, verbose_name='Автор')

    image = models.ImageField(
        upload_to='articles/%Y/%m/%d/',
        blank=True,
        null=True,
        verbose_name='Изображение'
    )

    objects = ArticleManager()
    all_objects = AllArticleManager()

    def get_absolute_url(self):
        return reverse('news:detail_article_by_id', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        # Сохраняем статью, чтобы получить id
        super().save(*args, **kwargs)
        if not self.slug:
            base_slug = slugify(unidecode.unidecode(self.title))
            unique_slug = base_slug
            num = 1
            while Article.objects.filter(slug=unique_slug).exists():
                unique_slug = f"{base_slug}-{num}"
                num += 1
            self.slug = unique_slug
        super().save(*args, **kwargs)


    class Meta:
        db_table = 'Articles'  # без указания этого параметра, таблица в БД будет называться 'news_artcile'
        verbose_name = 'Статья'  # единственное число для отображения в админке
        verbose_name_plural = 'Статьи'  # множественное число для отображения в админке
        # ordering = ['publication_date']  # указывает порядок сортировки модели по умолчанию
        # unique_together = (...)  # устанавливает уникальность для комбинации полей
        # index_together = (...)  # создаёт для нескольких полей
        # indexes = (...)  # определяет пользовательские индексы
        # abstract = True/False  # делает модель абстрактной, не создаёт таблицу БД, нужна только для наследования другими моделями данных
        # managed = True/False  # будет ли эта модель управляться (создание, удаление, изменение) с помощью Django или нет
        # permissions = [...]  # определяет пользовательские разрешения для модели

    def __str__(self):
        return self.title


class Like(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='likes')
    ip_address = models.GenericIPAddressField()

    def __str__(self):
        return f'Like by {self.ip_address} on {self.article}'


class Favorite(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='favorites')
    ip_address = models.GenericIPAddressField()

    def __str__(self):
        return f'Favorite by {self.ip_address} on {self.article}'


class ArticleHistory(models.Model):
    article = models.ForeignKey('Article', on_delete=models.CASCADE, related_name='history')
    user = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, blank=True, related_name='article_history')
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.article.title} — {self.timestamp.strftime('%d %b %Y %H:%M')}"


class ArticleHistoryDetail(models.Model):
    history = models.ForeignKey(ArticleHistory, on_delete=models.CASCADE, related_name='details')
    field_name = models.CharField(max_length=100)  # например, title, category, tags и т.д.
    old_value = models.TextField(blank=True, null=True)
    new_value = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.field_name}: {self.old_value} → {self.new_value}"


class Comment(models.Model):
    article = models.ForeignKey('Article', on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, blank=True, related_name='comments')
    content = models.TextField(verbose_name="Комментарий")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Комментарий от {self.user or 'Аноним'} на {self.article.title}"

    class Meta:
        ordering = ('created_at',)


class UserSubscription(models.Model):
    """
    Подписка одного пользователя (subscriber)
    на статьи другого пользователя‑автора (author).
    """
    subscriber = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="subscribed_authors",
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="followers",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("subscriber", "author")
        verbose_name = "Подписка на автора"
        verbose_name_plural = "Подписки на авторов"

    def __str__(self):
        return f"{self.subscriber} → {self.author}"


class TagSubscription(models.Model):
    """
    Подписка пользователя на теги.
    """
    subscriber = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="subscribed_tags",
    )
    tag = models.ForeignKey("Tag", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("subscriber", "tag")
        verbose_name = "Подписка на тег"
        verbose_name_plural = "Подписки на теги"

    def __str__(self):
        return f"{self.subscriber} → #{self.tag}"

news/forms.py
from django import forms

from .models import Article, Category, Comment, Tag


class ArticleForm(forms.ModelForm):

    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Article
        fields = ['title', 'content', 'category', 'tags', 'image']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите заголовок'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 5, 'placeholder': 'Введите текст статьи'}),
            'category': forms.Select(attrs={'class': 'form-select'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }
        label = {
            'category': 'Категория',
            'tags': 'Теги',
            'image': 'Обложка статьи'
        }


class CommentForm(forms.ModelForm):
    content = forms.CharField(
        label="Ваш комментарий",
        widget=forms.Textarea(attrs={'rows': 3, 'class': 'form-control', 'placeholder': 'Введите текст комментария'})
    )

    class Meta:
        model = Comment
        fields = ['content']


class ArticleUploadForm(forms.Form):
    json_file = forms.FileField(label='Загрузить JSON-файл', widget=forms.FileInput(attrs={'class': 'form-control'}))

    def clean_json_file(self):
        json_file = self.cleaned_data.get('json_file')
        if not json_file.name.endswith('.json'):
            raise forms.ValidationError('Файл должен быть в формате JSON.')
        return json_file

    def validate_json_data(self, data):
        errors = []
        existing_categories = Category.objects.values_list('name', flat=True)
        existing_tags = Tag.objects.values_list('name', flat=True)
        for item in data:
            fields = item['fields']
            title = fields['title']
            content = fields['content']
            category_name = fields['category']
            tags_names = fields['tags']
            if category_name not in existing_categories:
                errors.append(f"В новости '{title}' несуществующая категория '{category_name}'. Впишите одну из этих категорий в файл: {', '.join(existing_categories)}")
            for tag_name in tags_names:
                if tag_name not in existing_tags:
                    errors.append(f"В новости '{title}' несуществующий тег '{tag_name}'. Впишите один из этих тегов в файл: {', '.join(existing_tags)}")
        return errors

news/templates/include/article_preview.html
{% load customtags %}
<div class="card card-shadow">
    <div class="card-body">
        <h5 class="card-title">#{{ article.id }}. {{ article.title }}</h5>
        <p class="card-text">{{ article.content|truncatewords:7 }}</p>
        <p class="card-text"><a href="{% url 'news:get_news_by_category' article.category.id %}" class="text-decoration-none text-primary fw-bold category-link">{{ article.category }}</a></p>
        {% for tag in article.tags.all %}
            <a href="{% url 'news:get_news_by_tag' tag.id %}" class="text-decoration-none" style="color: {{ tag|random_color }};"><i class="bi bi-hash"></i>{{ tag.name|upper }}</a>
        {% endfor %}
        <p class="card-text d-flex justify-content-between">
            <small class="text-muted"><i class="bi bi-calendar"></i> {{ article.publication_date }}</small>
            <span><i class="bi bi-eye-fill"></i> {{ article.views }}</span>
            <form method="POST" action="{% url 'news:toggle_like' article.id %}" class="d-inline">
                {% csrf_token %}
                <button type="submit" class="btn btn-link p-0 text-black text-decoration-none">
                    {% if article|has_liked:user_ip %}
                        <i class="bi bi-balloon-heart-fill"></i> {{ article.likes.count }}
                    {% else %}
                        <i class="bi bi-balloon-heart"></i> {{ article.likes.count }}
                    {% endif %}
                </button>
            </form>
            <form method="POST" action="{% url 'news:toggle_favorite' article.id %}" class="d-inline">
                {% csrf_token %}
                <button type="submit" class="btn btn-link p-0 text-black text-decoration-none">
                    {% if article|has_favorited:user_ip %}
                        <i class="bi bi-star-fill"></i>
                    {% else %}
                        <i class="bi bi-star"></i>
                    {% endif %}
                </button>
            </form>
        </p>
         <p class="card-text"><i class="bi bi-person-fill"></i> {{ article.author|default:'Аноним' }}</p>
        <a href="{% url 'news:detail_article_by_id' article.id %}" class="btn btn-outline-secondary mt-2">Подробнее</a>
    </div>
</div>

news/templates/include/paginator.html
{% load customtags %}
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    {# Кнопки "Первая" и "Предыдущая" #}
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page=1" aria-label="First">
          <span aria-hidden="true">&laquo;&laquo;</span>
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <span class="page-link" aria-hidden="true">&laquo;&laquo;</span>
      </li>
      <li class="page-item disabled">
        <span class="page-link" aria-hidden="true">&laquo;</span>
      </li>
    {% endif %}

    {# Номера страниц с многоточиями #}
    {% paginate_pages page_obj as pages %}
    {% for p in pages %}
      {% if p == "..." %}
        <li class="page-item disabled">
          <span class="page-link">…</span>
        </li>
      {% else %}
        <li class="page-item {% if p == page_obj.number %}active{% endif %}">
          <a class="page-link" href="?page={{ p }}">{{ p }}</a>
        </li>
      {% endif %}
    {% endfor %}

    {# Кнопки "Следующая" и "Последняя" #}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
          <span aria-hidden="true">&raquo;&raquo;</span>
        </a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <span class="page-link" aria-hidden="true">&raquo;</span>
      </li>
      <li class="page-item disabled">
        <span class="page-link" aria-hidden="true">&raquo;&raquo;</span>
      </li>
    {% endif %}
  </ul>
</nav>

news/templates/include/rubricator.html
<div class="card border-0 bg-transparent">
    <div class="card-body p-0">
        <ul class="list-group list-group-flush">
            {% for category in categories %}
                {% if category.article_set.count > 0 %}
                    <a href="{% url 'news:get_news_by_category' category.id %}"
                       class="list-group-item list-group-item-action d-flex justify-content-between align-items-center bg-transparent text-light hover-effect {% if active_category_id|stringformat:"s" == category.id|stringformat:"s" %}active-category{% endif %}">
                        {{ category.name }}
                        <span class="badge bg-primary rounded-pill">{{ category.article_set.count }}</span>
                    </a>
                {% endif %}
            {% endfor %}
        </ul>
    </div>
</div>

news/templates/include/search_form.html
<form method="GET" action="{% url 'news:search_news' %}" class="form-inline my-2 my-lg-0 mb-4">
    <div class="input-group">
        <input class="form-control" type="search" placeholder="Поиск" aria-label="Search" name="q">
        <button class="btn btn-outline-success" type="submit">
            <i class="bi bi-search"></i>
        </button>
    </div>
</form>
<h1 class="text-center mb-4"></h1>