itg/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from itg import settings
from news import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.MainView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('news/', include('news.urls', namespace='news')),
    path('users/', include('users.urls', namespace='users')),

    # Общие URL allauth
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

users/urls.py
# users/urls.py
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    path('profile/', views.ProfileUpdateView.as_view(), name='profile'),
    path('profile/articles/', views.ProfileArticlesView.as_view(), name='profile_articles'),
    path('profile/activity/', views.ProfileActivityView.as_view(), name='profile_activity'),
]

templates/include/form_field.html
{# templates/include/form_field.html #}
<div class="mb-3">
  <label for="{{ field.id_for_label }}" class="form-label fw-bold">{{ field.label }}</label>
  {{ field }}
  {% if field.errors %}
    <div class="alert alert-danger mt-2">
      {{ field.errors }}
    </div>
  {% endif %}
</div>

templates/include/nav_menu.html
<ul class="navbar-nav">
    {% for item in menu %}
        <li class="nav-item">
            <a class="nav-link" href="{% url item.url_name %}">{{ item.title }}</a>
        </li>
        {% if not forloop.last %}
            <li class="nav-item"><hr class="dropdown-divider"/></li>
        {% endif %}
    {% endfor %}
    {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:profile' %}">Привет, {{ user.username }}!</a>
        </li>
        <li class="nav-item">
          <form method="post" action="{% url 'account_logout' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-link nav-link">Выйти</button>
          </form>
        </li>
    {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_login' %}">Войти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_signup' %}">Регистрация</a>
        </li>
    {% endif %}
</ul>